default: true

MD013: false  # Line length
MD033: false  # Inline HTML
MD041: false  # First line in file should be a top level heading
MD026: false  # Trailing punctuation in heading
MD002: false  # First heading should be a top level heading

MD014: false  # Dollar signs used before commands without showing output
MD040: false  # Fenced code blocks should have a language specified

# Chirpy-specific rules
MD001: false  # Allow multiple top-level headings
MD024: false  # Allow multiple headings with the same content
MD025: false  # Allow multiple top-level headings in the same document
MD036: false  # Emphasis used instead of a heading 